#ifndef _IR_AQUARIUM_TIMER_CONF_H_
#define _IR_AQUARIUM_TIMER_CONF_H_

#define IRALT_WIFI_SSID  "<SSID>"
#define IRALT_WIFI_PSK   "<PASSWORD>"
#define IRALT_NTP_SERVER "<NTP.SERVER.HOST>"

#endif /* _IR_AQUARIUM_TIMER_CONF_H_ */
